# Generated by Django 5.0.7 on 2024-08-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_motivebypass_tipstatie_tipuri_transportatori_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bypass',
            name='cisterna',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='motiv',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='sofer',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='tip_statie',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='transportator',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='utilizator',
        ),
        migrations.RemoveField(
            model_name='cisterne',
            name='companie',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tip_statie',
        ),
        migrations.RemoveField(
            model_name='depozit',
            name='tip_statie',
        ),
        migrations.RemoveField(
            model_name='particular',
            name='tip_statie',
        ),
        migrations.RemoveField(
            model_name='soferi',
            name='companie',
        ),
        migrations.RemoveField(
            model_name='statie',
            name='tip_statie',
        ),
        migrations.RemoveField(
            model_name='test',
            name='tip_statie',
        ),
        migrations.DeleteModel(
            name='MotiveBypass',
        ),
        migrations.DeleteModel(
            name='Tipuri',
        ),
        migrations.DeleteModel(
            name='Bypass',
        ),
        migrations.DeleteModel(
            name='Cisterne',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Depozit',
        ),
        migrations.DeleteModel(
            name='Particular',
        ),
        migrations.DeleteModel(
            name='Soferi',
        ),
        migrations.DeleteModel(
            name='Transportatori',
        ),
        migrations.DeleteModel(
            name='Statie',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TipStatie',
        ),
    ]
