# Generated by Django 5.0.7 on 2024-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bypass_client_bypass_cod_statie_bypass_depozit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bypass',
            name='info_statie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
