# Generated by Django 5.0.7 on 2024-08-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bypass_info_statie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='info_statie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='depozit',
            name='info_statie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='particular',
            name='info_statie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statie',
            name='info_statie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='info_statie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
