# Generated by Django 5.0.7 on 2024-08-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_client_info_statie_alter_depozit_info_statie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bypass',
            name='client',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='depozit',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='particular',
        ),
        migrations.RemoveField(
            model_name='bypass',
            name='test',
        ),
        migrations.AlterField(
            model_name='bypass',
            name='cisterna',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='cod_statie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='info_statie',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='motiv',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='observatii',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='sofer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='tip',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='tip_statie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipstatie'),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='transportator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bypass',
            name='utilizator',
            field=models.CharField(max_length=255),
        ),
    ]
